### ISSUE TITLE
Run EsLint before pushing

### ISSUE THREAD

**Issue by nextrie** [NessMC/quark-lang#3]
**Is your feature request related to a problem? Please describe.**
The currently pushed version of the project has EsLint errors
![image](https://user-images.githubusercontent.com/40547005/88445194-6dd2de00-ce21-11ea-9658-b44707f7c5ae.png)

**Describe the solution you'd like**
Run `npm run lint` on the project before pushing a new feature to avoid new lint errors

**Describe alternatives you've considered**
Configure EsLint on your IDE to avoid to run `npm run lint` command

**Comment by NessMC** [comment]
Hello ! First of all, I wanted to thank you for your contribution to the project! Your idea to run the linter before committing is great. So I implemented it to the project and I used : 
 - Husky: Package that handles git hooks in particular.
 - Lint staged: Package that cleans the modified code with ESlint.

Greetings,
Ness.
