### ISSUE TITLE
Write and run tests

### ISSUE THREAD

**Issue by nextrie** [NessMC/quark-lang#4]
**Is your feature request related to a problem? Please describe.** A clear and
Every new function in Quark Lang should have its own test, so that upcoming features does not break existing ones

**Describe the solution you'd like** A clear and concise description of what you
Create a test for every function you create. It brings code stability and also examples on how to use your functions.
Run every tests before pushing so you ensure nothing broke.

**Comment by NessMC** [comment]
Hello ! First of all, I wanted to thank you for your contribution to the project! The tests were initially planned and are already ready to be written. So no worries about that :)

Greetings,
Ness.
